//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int grpId { get; set; }
        public string grpName { get; set; }
        public string grpDesc { get; set; }
        public string grpDate { get; set; }
        public Nullable<int> studId { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
