//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultiQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MultiQuestion()
        {
            this.MultiAnswers1 = new HashSet<MultiAnswers>();
        }
    
        public int mqQuestionID { get; set; }
        public string mqQuestionDesc { get; set; }
        public Nullable<int> mqEachMarks { get; set; }
        public string mqCorrectAnswer { get; set; }
        public Nullable<int> asID { get; set; }
    
        public virtual Assessment Assessment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MultiAnswers> MultiAnswers1 { get; set; }
    }
}
