//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultiAnswer
    {
        public int maAnswerID { get; set; }
        public string maAnswerDesc { get; set; }
        public string maAnswerLabel { get; set; }
        public Nullable<int> mqQuestionID { get; set; }
    
        public virtual MultiQuestion MultiQuestion { get; set; }
    }
}
