//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAssessment
    {
        public int stasID { get; set; }
        public Nullable<int> stasScore { get; set; }
        public string stasAnswerGiven { get; set; }
        public Nullable<int> mqQuestionID { get; set; }
        public Nullable<int> studID { get; set; }
    
        public virtual MultiQuestion MultiQuestion { get; set; }
        public virtual Student Student { get; set; }
    }
}
